#!/bin/bash

# Nginx Reverse Proxy Setup Script for Frontend
# Bu script frontend'i 3000 portundan 80 portuna yönlendirir

set -e

echo "🔧 Nginx Reverse Proxy Setup Script"
echo "===================================="
echo ""

# Nginx'in kurulu olup olmadığını kontrol et
if ! command -v nginx &> /dev/null; then
    echo "📦 Nginx kuruluyor..."
    sudo apt-get update
    sudo apt-get install -y nginx
    echo "✅ Nginx kuruldu"
else
    echo "✅ Nginx zaten kurulu"
fi

echo ""

# Mevcut nginx config'i kontrol et
CONFIG_FILE="/etc/nginx/sites-available/ebars-frontend"
ENABLED_FILE="/etc/nginx/sites-enabled/ebars-frontend"

# Server IP veya domain'i al
read -p "Server IP veya domain adını girin (örn: 65.109.230.236 veya ebars.example.com): " SERVER_NAME

if [ -z "$SERVER_NAME" ]; then
    echo "❌ Server IP/domain gerekli!"
    exit 1
fi

echo ""
echo "📝 Nginx config dosyası oluşturuluyor..."

# Config dosyasını oluştur
sudo tee "$CONFIG_FILE" > /dev/null <<EOF
# Nginx Reverse Proxy Configuration for Frontend
# Generated by setup-nginx-frontend.sh

server {
    listen 80;
    server_name $SERVER_NAME;

    # Log dosyaları
    access_log /var/log/nginx/ebars-frontend-access.log;
    error_log /var/log/nginx/ebars-frontend-error.log;

    # Client body size limit (dosya yükleme için)
    client_max_body_size 100M;

    # Frontend'e proxy
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        
        # Headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        
        # WebSocket desteği (Next.js için)
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        
        # Buffering
        proxy_buffering off;
        proxy_request_buffering off;
    }

    # API Gateway'e proxy (opsiyonel)
    location /api/ {
        proxy_pass http://localhost:8000;
        proxy_http_version 1.1;
        
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Auth Service'e proxy (opsiyonel)
    location /auth/ {
        proxy_pass http://localhost:8006;
        proxy_http_version 1.1;
        
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Static files caching (Next.js için)
    location /_next/static/ {
        proxy_pass http://localhost:3000;
        proxy_cache_valid 200 60m;
        add_header Cache-Control "public, immutable";
    }
}
EOF

echo "✅ Config dosyası oluşturuldu: $CONFIG_FILE"
echo ""

# Default nginx config'i devre dışı bırak (eğer varsa)
if [ -L "/etc/nginx/sites-enabled/default" ]; then
    echo "🗑️  Default nginx config devre dışı bırakılıyor..."
    sudo rm /etc/nginx/sites-enabled/default
fi

# Symlink oluştur
if [ -L "$ENABLED_FILE" ]; then
    echo "⚠️  Mevcut symlink kaldırılıyor..."
    sudo rm "$ENABLED_FILE"
fi

echo "🔗 Symlink oluşturuluyor..."
sudo ln -s "$CONFIG_FILE" "$ENABLED_FILE"
echo "✅ Symlink oluşturuldu: $ENABLED_FILE"
echo ""

# Nginx config'i test et
echo "🧪 Nginx config test ediliyor..."
if sudo nginx -t; then
    echo "✅ Nginx config geçerli!"
else
    echo "❌ Nginx config hatası! Lütfen kontrol edin."
    exit 1
fi

echo ""

# Nginx'i yeniden başlat
echo "🔄 Nginx yeniden başlatılıyor..."
sudo systemctl restart nginx

# Nginx durumunu kontrol et
if sudo systemctl is-active --quiet nginx; then
    echo "✅ Nginx başarıyla başlatıldı!"
else
    echo "❌ Nginx başlatılamadı! Logları kontrol edin:"
    echo "   sudo journalctl -u nginx -n 50"
    exit 1
fi

echo ""
echo "📊 Nginx durumu:"
sudo systemctl status nginx --no-pager -l

echo ""
echo "✅ Kurulum tamamlandı!"
echo ""
echo "🌐 Frontend artık şu adresten erişilebilir:"
echo "   http://$SERVER_NAME"
echo ""
echo "📝 Yeni sayfalar:"
echo "   - http://$SERVER_NAME/survey"
echo "   - http://$SERVER_NAME/system-info"
echo "   - http://$SERVER_NAME/admin/survey-results"
echo ""
echo "🔍 Logları kontrol etmek için:"
echo "   sudo tail -f /var/log/nginx/ebars-frontend-access.log"
echo "   sudo tail -f /var/log/nginx/ebars-frontend-error.log"
























