#!/bin/bash

# Nginx HTTPS Reverse Proxy Setup Script for EBARS
# SSL sertifikası kurulduktan sonra bu script'i çalıştırın

set -e

echo "🔒 Nginx HTTPS Reverse Proxy Setup Script"
echo "=========================================="
echo ""

# Nginx'in kurulu olup olmadığını kontrol et
if ! command -v nginx &> /dev/null; then
    echo "📦 Nginx kuruluyor..."
    sudo apt-get update
    sudo apt-get install -y nginx
    echo "✅ Nginx kuruldu"
else
    echo "✅ Nginx zaten kurulu"
fi

echo ""

# SSL sertifikasının var olup olmadığını kontrol et
SSL_CERT="/etc/letsencrypt/live/ebars.kodleon.com/fullchain.pem"
SSL_KEY="/etc/letsencrypt/live/ebars.kodleon.com/privkey.pem"

if [ ! -f "$SSL_CERT" ] || [ ! -f "$SSL_KEY" ]; then
    echo "❌ SSL sertifikası bulunamadı!"
    echo "   Önce SSL sertifikasını kurmalısınız:"
    echo "   sudo certbot certonly --nginx -d ebars.kodleon.com"
    echo ""
    echo "   Veya otomatik script ile:"
    echo "   ./setup-ssl-hetzner.sh"
    exit 1
fi

echo "✅ SSL sertifikası bulundu"
echo ""

# Config dosyası yolları
CONFIG_FILE="/etc/nginx/sites-available/ebars-https"
ENABLED_FILE="/etc/nginx/sites-enabled/ebars-https"

# HTTPS config dosyasını oluştur
echo "📝 HTTPS Nginx config dosyası oluşturuluyor..."

sudo tee "$CONFIG_FILE" > /dev/null <<'EOF'
# Nginx HTTPS Reverse Proxy Configuration for EBARS
# Generated by setup-nginx-https.sh

# HTTP'den HTTPS'e yönlendirme
server {
    listen 80;
    server_name ebars.kodleon.com;

    # Let's Encrypt için ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # Tüm diğer istekleri HTTPS'e yönlendir
    location / {
        return 301 https://$server_name$request_uri;
    }
}

# HTTPS Server Block
server {
    listen 443 ssl http2;
    server_name ebars.kodleon.com;

    # SSL Sertifikaları (Let's Encrypt)
    ssl_certificate /etc/letsencrypt/live/ebars.kodleon.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ebars.kodleon.com/privkey.pem;

    # SSL Güvenlik Ayarları
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;

    # HSTS (HTTP Strict Transport Security)
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Log dosyaları
    access_log /var/log/nginx/ebars-https-access.log;
    error_log /var/log/nginx/ebars-https-error.log;

    # Client body size limit (dosya yükleme için)
    client_max_body_size 100M;

    # Frontend'e proxy
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        
        # Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        
        # WebSocket desteği (Next.js için)
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeouts (uzun süren işlemler için)
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        
        # Buffering
        proxy_buffering off;
        proxy_request_buffering off;
    }

    # API Gateway'e proxy - HTTPS üzerinden
    location /api/ {
        proxy_pass http://localhost:8000;
        proxy_http_version 1.1;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        
        # CORS headers (backend'de de var ama ekstra güvenlik için)
        add_header 'Access-Control-Allow-Origin' 'https://ebars.kodleon.com' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        
        # OPTIONS request handling
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'https://ebars.kodleon.com' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }
        
        # Timeouts (uzun süren RAG sorguları için)
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        
        # Buffering
        proxy_buffering off;
        proxy_request_buffering off;
    }

    # Auth Service'e proxy - HTTPS üzerinden
    location /auth/ {
        proxy_pass http://localhost:8006;
        proxy_http_version 1.1;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Static files caching (Next.js için)
    location /_next/static/ {
        proxy_pass http://localhost:3000;
        proxy_cache_valid 200 60m;
        add_header Cache-Control "public, immutable";
    }
}
EOF

echo "✅ Config dosyası oluşturuldu: $CONFIG_FILE"
echo ""

# Eski HTTP config'i devre dışı bırak (eğer varsa)
if [ -L "/etc/nginx/sites-enabled/ebars-frontend" ]; then
    echo "🗑️  Eski HTTP config devre dışı bırakılıyor..."
    sudo rm /etc/nginx/sites-enabled/ebars-frontend
fi

# Default nginx config'i devre dışı bırak (eğer varsa)
if [ -L "/etc/nginx/sites-enabled/default" ]; then
    echo "🗑️  Default nginx config devre dışı bırakılıyor..."
    sudo rm /etc/nginx/sites-enabled/default
fi

# Symlink oluştur
if [ -L "$ENABLED_FILE" ]; then
    echo "⚠️  Mevcut symlink kaldırılıyor..."
    sudo rm "$ENABLED_FILE"
fi

echo "🔗 Symlink oluşturuluyor..."
sudo ln -s "$CONFIG_FILE" "$ENABLED_FILE"
echo "✅ Symlink oluşturuldu: $ENABLED_FILE"
echo ""

# Nginx config'i test et
echo "🧪 Nginx config test ediliyor..."
if sudo nginx -t; then
    echo "✅ Nginx config geçerli!"
else
    echo "❌ Nginx config hatası! Lütfen kontrol edin."
    exit 1
fi

echo ""

# Nginx'i yeniden başlat
echo "🔄 Nginx yeniden başlatılıyor..."
sudo systemctl restart nginx

# Nginx durumunu kontrol et
if sudo systemctl is-active --quiet nginx; then
    echo "✅ Nginx başarıyla başlatıldı!"
else
    echo "❌ Nginx başlatılamadı! Logları kontrol edin:"
    echo "   sudo journalctl -u nginx -n 50"
    exit 1
fi

echo ""
echo "📊 Nginx durumu:"
sudo systemctl status nginx --no-pager -l

echo ""
echo "✅ HTTPS kurulum tamamlandı!"
echo ""
echo "🌐 Frontend artık şu adresten erişilebilir:"
echo "   https://ebars.kodleon.com"
echo ""
echo "🔒 HTTP istekleri otomatik olarak HTTPS'e yönlendirilecek"
echo ""
echo "🔍 Logları kontrol etmek için:"
echo "   sudo tail -f /var/log/nginx/ebars-https-access.log"
echo "   sudo tail -f /var/log/nginx/ebars-https-error.log"




