"""
RAGAS Evaluation Routes

Provides endpoints for RAG evaluation using RAGAS metrics:
- Faithfulness: Measures if the answer is grounded in the given context
- Answer Relevancy: Measures how relevant the answer is to the question
- Context Precision: Measures the precision of the retrieved context
- Context Recall: Measures the recall of the retrieved context

Batch Evaluation:
- Start batch evaluation with multiple questions
- Track progress and status
- Collect production data automatically
- Compare different methodologies
"""

import logging
import os
import uuid
import asyncio
import json
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Dict, Any
from fastapi import APIRouter, HTTPException, BackgroundTasks, Request
from pydantic import BaseModel, Field
import requests
import httpx

logger = logging.getLogger(__name__)

# RAGAS Service URL
RAGAS_SERVICE_URL = os.getenv(
    'RAGAS_SERVICE_URL',
    os.getenv('RAGAS_SERVICE_HOST', 'http://ragas-service:8010')
)
# Ensure we have the full URL
if not RAGAS_SERVICE_URL.startswith('http'):
    RAGAS_SERVICE_PORT = os.getenv('RAGAS_SERVICE_PORT', '8010')
    RAGAS_SERVICE_URL = f'http://{RAGAS_SERVICE_URL}:{RAGAS_SERVICE_PORT}'

# API Gateway URL (for getting RAG responses)
API_GATEWAY_URL = os.getenv('API_GATEWAY_URL', os.getenv('API_GATEWAY_INTERNAL_URL', 'http://localhost:8000'))
if API_GATEWAY_URL.startswith('https://'):
    API_GATEWAY_URL = API_GATEWAY_URL.replace('https://', 'http://')

router = APIRouter(prefix="/rag-metrics", tags=["RAG Metrics (RAGAS)"])

# Test results storage (similar to test_simulation_routes)
RAGAS_TEST_STORAGE: Dict[str, Any] = {}

# Database for RAGAS test persistence
RAGAS_TEST_DB_PATH = Path("data/ragas_test_results.db")

def _init_ragas_test_db():
    """Initialize RAGAS test results database"""
    RAGAS_TEST_DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with sqlite3.connect(RAGAS_TEST_DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS ragas_test_results (
                test_id TEXT PRIMARY KEY,
                data TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

def _save_ragas_test_to_db(test_id: str, test_data: Dict[str, Any]):
    """Save RAGAS test data to database"""
    try:
        with sqlite3.connect(RAGAS_TEST_DB_PATH) as conn:
            conn.execute("""
                INSERT OR REPLACE INTO ragas_test_results (test_id, data, updated_at)
                VALUES (?, ?, CURRENT_TIMESTAMP)
            """, (test_id, json.dumps(test_data)))
    except Exception as e:
        logger.warning(f"Failed to save RAGAS test to DB: {e}")

def _load_ragas_test_from_db(test_id: str) -> Optional[Dict[str, Any]]:
    """Load RAGAS test data from database"""
    try:
        with sqlite3.connect(RAGAS_TEST_DB_PATH) as conn:
            cursor = conn.execute("SELECT data FROM ragas_test_results WHERE test_id = ?", (test_id,))
            row = cursor.fetchone()
            if row:
                return json.loads(row[0])
    except Exception as e:
        logger.warning(f"Failed to load RAGAS test from DB: {e}")
    return None

# Initialize database on startup
_init_ragas_test_db()


class RAGASEvaluationRequest(BaseModel):
    """Request model for RAGAS evaluation"""
    question: str = Field(..., description="The question being asked")
    answer: str = Field(..., description="The answer generated by the RAG system")
    contexts: List[str] = Field(..., description="List of context documents used to generate the answer")
    ground_truth: Optional[str] = Field(None, description="Optional ground truth answer for context precision/recall")


class RAGASEvaluationResponse(BaseModel):
    """Response model for RAGAS evaluation"""
    faithfulness: float = Field(..., description="Faithfulness score (0-1)")
    answer_relevancy: float = Field(..., description="Answer relevancy score (0-1)")
    context_precision: Optional[float] = Field(None, description="Context precision score (0-1), requires ground_truth")
    context_recall: Optional[float] = Field(None, description="Context recall score (0-1), requires ground_truth")
    overall_score: float = Field(..., description="Overall average score")
    metrics_available: List[str] = Field(..., description="List of metrics that were calculated")


# Batch Evaluation Models (similar to test-simulation)
class RAGASBatchStartRequest(BaseModel):
    """Request model for starting RAGAS batch evaluation"""
    testName: str = Field(..., description="Name of the test")
    questions: List[str] = Field(..., description="List of questions to test")
    sessionId: str = Field(..., description="Session ID for testing")
    sessionSettings: Optional[Dict[str, Any]] = Field(default=None, description="Session RAG settings")
    expectedAnswers: Optional[Dict[int, str]] = Field(default=None, description="Optional map of question index to expected answer (ground truth)")
    useProductionData: bool = Field(default=False, description="Use production queries from session instead of provided questions")
    maxQuestions: Optional[int] = Field(default=None, description="Maximum number of questions to use from production data")


class RAGASQuestionResult(BaseModel):
    """Result for a single question evaluation"""
    question_id: int
    question: str
    answer: str
    contexts: List[str]
    ground_truth: Optional[str]
    ragas_metrics: RAGASEvaluationResponse
    response_time_ms: float
    retrieval_count: int


@router.get("/health")
async def health_check():
    """Health check endpoint"""
    try:
        # Check if RAGAS service is available
        async with httpx.AsyncClient(timeout=5.0) as client:
            response = await client.get(f"{RAGAS_SERVICE_URL}/health")
            if response.status_code == 200:
                return {
                    "status": "healthy",
                    "ragas_service": "available",
                    "ragas_service_url": RAGAS_SERVICE_URL
                }
            else:
                return {
                    "status": "degraded",
                    "ragas_service": "unavailable",
                    "ragas_service_url": RAGAS_SERVICE_URL,
                    "error": f"RAGAS service returned status {response.status_code}"
                }
    except Exception as e:
        logger.error(f"Health check failed: {e}")
        return {
            "status": "unhealthy",
            "ragas_service": "unavailable",
            "ragas_service_url": RAGAS_SERVICE_URL,
            "error": str(e)
        }


@router.post("/evaluate", response_model=RAGASEvaluationResponse)
async def evaluate_rag(request: RAGASEvaluationRequest):
    """
    Evaluate RAG performance using RAGAS metrics
    
    This endpoint forwards the evaluation request to the RAGAS service
    and returns the calculated metrics.
    """
    try:
        logger.info(f"Evaluating RAG performance for question: {request.question[:50]}...")
        
        # Forward request to RAGAS service
        # Increased timeout to 300 seconds (5 minutes) for RAGAS evaluation
        async with httpx.AsyncClient(timeout=300.0) as client:
            logger.info(f"📡 Sending request to RAGAS service at {RAGAS_SERVICE_URL}/evaluate")
            logger.debug(f"   Question: {request.question[:50]}...")
            logger.debug(f"   Answer length: {len(request.answer)} chars")
            logger.debug(f"   Contexts count: {len(request.contexts)}")
            logger.debug(f"   Ground truth: {'Yes' if request.ground_truth else 'No'}")
            
            response = await client.post(
                f"{RAGAS_SERVICE_URL}/evaluate",
                json={
                    "question": request.question,
                    "answer": request.answer,
                    "contexts": request.contexts,
                    "ground_truth": request.ground_truth
                }
            )
            
            logger.info(f"📥 RAGAS service response: {response.status_code}")
            
            if response.status_code != 200:
                try:
                    error_text = await response.aread()
                    error_str = error_text.decode() if error_text else "Unknown error"
                    logger.error(f"❌ RAGAS service error: {response.status_code} - {error_str[:500]}")
                    raise HTTPException(
                        status_code=response.status_code,
                        detail=f"RAGAS service error: {error_str[:500]}"
                    )
                except Exception as e:
                    logger.error(f"❌ Failed to read error response: {e}")
                    raise HTTPException(
                        status_code=response.status_code,
                        detail=f"RAGAS service returned status {response.status_code}"
                    )
            
            # Parse response with better error handling
            try:
                response_text = await response.aread()
                if not response_text:
                    logger.error("❌ RAGAS service returned empty response")
                    raise HTTPException(
                        status_code=502,
                        detail="RAGAS service returned empty response"
                    )
                
                result = json.loads(response_text.decode())
                logger.info(f"✅ RAGAS response parsed successfully")
                logger.debug(f"   Result keys: {list(result.keys())}")
                
            except json.JSONDecodeError as e:
                logger.error(f"❌ Failed to parse RAGAS response as JSON: {e}")
                logger.error(f"   Response text (first 500 chars): {response_text.decode()[:500] if response_text else 'None'}")
                raise HTTPException(
                    status_code=502,
                    detail=f"RAGAS service returned invalid JSON: {str(e)[:200]}"
                )
            except Exception as e:
                logger.error(f"❌ Error reading RAGAS response: {e}")
                raise HTTPException(
                    status_code=502,
                    detail=f"Failed to read RAGAS service response: {str(e)[:200]}"
                )
            
            # Validate response has required fields
            if not isinstance(result, dict):
                logger.error(f"❌ RAGAS response is not a dictionary: {type(result)}")
                raise HTTPException(
                    status_code=502,
                    detail="RAGAS service returned invalid response format"
                )
            
            # Determine which metrics were calculated
            metrics_available = ["faithfulness", "answer_relevancy"]
            if request.ground_truth:
                metrics_available.extend(["context_precision", "context_recall"])
            
            # Extract metrics with validation
            faithfulness = result.get("faithfulness")
            answer_relevancy = result.get("answer_relevancy")
            overall_score = result.get("overall_score")
            
            # Log extracted metrics
            logger.info(f"📊 Extracted metrics:")
            logger.info(f"   Faithfulness: {faithfulness}")
            logger.info(f"   Answer Relevancy: {answer_relevancy}")
            logger.info(f"   Overall Score: {overall_score}")
            
            # Validate required metrics
            if faithfulness is None or answer_relevancy is None:
                logger.warning(f"⚠️ Some required metrics are missing: faithfulness={faithfulness}, answer_relevancy={answer_relevancy}")
            
            return RAGASEvaluationResponse(
                faithfulness=faithfulness if faithfulness is not None else 0.0,
                answer_relevancy=answer_relevancy if answer_relevancy is not None else 0.0,
                context_precision=result.get("context_precision"),
                context_recall=result.get("context_recall"),
                overall_score=overall_score if overall_score is not None else 0.0,
                metrics_available=metrics_available
            )
            
    except httpx.TimeoutException:
        logger.error("RAGAS service timeout")
        raise HTTPException(
            status_code=504,
            detail="RAGAS service request timed out. The evaluation may take longer than expected."
        )
    except httpx.ConnectError:
        logger.error(f"Could not connect to RAGAS service at {RAGAS_SERVICE_URL}")
        raise HTTPException(
            status_code=503,
            detail=f"RAGAS service is unavailable at {RAGAS_SERVICE_URL}. Please check if the service is running."
        )
    except Exception as e:
        logger.error(f"Evaluation error: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Evaluation failed: {str(e)}"
        )


# Helper function to execute RAG query and get response with contexts
async def execute_rag_query(session_id: str, question: str, session_settings: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Execute RAG query and return answer with contexts (similar to test-simulation)"""
    import time
    start_time = time.time()
    
    try:
        # Use API Gateway's /rag/query endpoint (same as test-simulation)
        async with httpx.AsyncClient(timeout=120.0, verify=False) as client:
            response = await client.post(
                f"{API_GATEWAY_URL}/rag/query",
                json={
                    "session_id": session_id,
                    "query": question,
                    "top_k": 5,
                    "use_rerank": True,
                    "min_score": 0.1,
                    "max_context_chars": 8000,
                    "use_direct_llm": False,
                    "disable_aprag": True,  # Disable personalization for consistent evaluation
                    "use_crag": False,
                    "session_settings": session_settings
                }
            )
            
            execution_time = (time.time() - start_time) * 1000
            
            if response.status_code == 200:
                try:
                    result = response.json()
                    
                    # Validate response structure
                    if not isinstance(result, dict):
                        logger.error(f"RAG query returned non-dict response: {type(result)}")
                        return {
                            "success": False,
                            "error": "Invalid response format from RAG service",
                            "answer": "",
                            "contexts": [],
                            "sources": [],
                            "response_time_ms": execution_time
                        }
                    
                    # Extract answer and contexts
                    answer = result.get("answer", "")
                    sources = result.get("sources", [])
                    contexts = []
                    
                    if not sources:
                        logger.warning(f"No sources returned from RAG query")
                    
                    for source in sources:
                        if isinstance(source, dict):
                            content = source.get("content") or source.get("chunk_text") or source.get("text", "")
                            if content:
                                contexts.append(content)
                        elif isinstance(source, str):
                            contexts.append(source)
                    
                    if not answer:
                        logger.warning(f"Empty answer returned from RAG query")
                    
                    logger.info(f"✅ RAG query successful: answer_length={len(answer)}, contexts_count={len(contexts)}")
                    
                    return {
                        "success": True,
                        "answer": answer,
                        "contexts": contexts,
                        "sources": sources,
                        "response_time_ms": execution_time
                    }
                except json.JSONDecodeError as e:
                    logger.error(f"Failed to parse RAG response as JSON: {e}")
                    return {
                        "success": False,
                        "error": f"Failed to parse RAG response: {str(e)[:200]}",
                        "answer": "",
                        "contexts": [],
                        "sources": [],
                        "response_time_ms": execution_time
                    }
            else:
                try:
                    error_text = await response.aread()
                    error_str = error_text.decode()[:500] if error_text else f"HTTP {response.status_code}"
                    logger.error(f"RAG query failed: {response.status_code} - {error_str}")
                    return {
                        "success": False,
                        "error": f"API Error: {response.status_code} - {error_str}",
                        "answer": "",
                        "contexts": [],
                        "sources": [],
                        "response_time_ms": execution_time
                    }
                except Exception as e:
                    logger.error(f"Failed to read error response: {e}")
                    return {
                        "success": False,
                        "error": f"API Error: {response.status_code} - Failed to read error message",
                        "answer": "",
                        "contexts": [],
                        "sources": [],
                        "response_time_ms": execution_time
                    }
    except Exception as e:
        execution_time = (time.time() - start_time) * 1000
        logger.error(f"Failed to execute RAG query: {e}")
        return {
            "success": False,
            "error": str(e),
            "answer": "",
            "contexts": [],
            "sources": [],
            "response_time_ms": execution_time
        }


# Background task for batch evaluation
async def execute_ragas_batch_evaluation(
    test_id: str,
    questions: List[str],
    session_id: str,
    session_settings: Optional[Dict[str, Any]],
    expected_answers: Optional[Dict[int, str]]
):
    """Execute batch RAGAS evaluation in background"""
    try:
        test_data = RAGAS_TEST_STORAGE.get(test_id)
        if not test_data:
            test_data = _load_ragas_test_from_db(test_id)
            if not test_data:
                logger.error(f"Test {test_id} not found")
                return
            RAGAS_TEST_STORAGE[test_id] = test_data
        
        test_data["status"] = "running"
        test_data["current_question"] = 0
        test_data["total_questions"] = len(questions)
        test_data["results"] = []
        
        _save_ragas_test_to_db(test_id, test_data)
        
        results = []
        total_questions = len(questions)
        
        for i, question in enumerate(questions):
            try:
                test_data["current_question"] = i + 1
                progress = ((i + 1) / total_questions) * 100
                test_data["progress"] = round(progress, 1)
                _save_ragas_test_to_db(test_id, test_data)
                
                logger.info(f"Processing question {i+1}/{total_questions}: {question[:50]}...")
                
                # Execute RAG query
                rag_result = await execute_rag_query(session_id, question, session_settings)
                
                if not rag_result["success"]:
                    logger.error(f"RAG query failed for question {i+1}")
                    results.append({
                        "question_id": i + 1,
                        "question": question,
                        "success": False,
                        "error": rag_result.get("error", "RAG query failed")
                    })
                    continue
                
                # Get ground truth if available
                ground_truth = expected_answers.get(i) if expected_answers else None
                
                # Validate RAG result before evaluation
                if not rag_result.get("answer"):
                    logger.warning(f"Question {i+1} has empty answer, skipping RAGAS evaluation")
                    results.append({
                        "question_id": i + 1,
                        "question": question,
                        "success": False,
                        "error": "Empty answer from RAG query"
                    })
                    continue
                
                if not rag_result.get("contexts"):
                    logger.warning(f"Question {i+1} has no contexts, RAGAS evaluation may be limited")
                
                # Evaluate with RAGAS
                try:
                    ragas_request = RAGASEvaluationRequest(
                        question=question,
                        answer=rag_result["answer"],
                        contexts=rag_result["contexts"] or [""],  # Ensure at least empty list
                        ground_truth=ground_truth
                    )
                    
                    logger.info(f"Evaluating question {i+1} with RAGAS...")
                    ragas_result = await evaluate_rag(ragas_request)
                    
                    # Validate RAGAS result
                    if not ragas_result:
                        logger.error(f"RAGAS returned empty result for question {i+1}")
                        results.append({
                            "question_id": i + 1,
                            "question": question,
                            "success": False,
                            "error": "RAGAS evaluation returned empty result"
                        })
                        continue
                    
                    # Convert to dict safely
                    ragas_metrics = ragas_result.dict() if hasattr(ragas_result, 'dict') else ragas_result
                    
                    logger.info(f"✅ Question {i+1} evaluated successfully: faithfulness={ragas_metrics.get('faithfulness')}, answer_relevancy={ragas_metrics.get('answer_relevancy')}")
                    
                    results.append({
                        "question_id": i + 1,
                        "question": question,
                        "answer": rag_result["answer"],
                        "contexts": rag_result["contexts"],
                        "ground_truth": ground_truth,
                        "ragas_metrics": ragas_metrics,
                        "response_time_ms": rag_result["response_time_ms"],
                        "retrieval_count": len(rag_result["contexts"]),
                        "success": True
                    })
                except HTTPException as http_e:
                    logger.error(f"HTTP error evaluating question {i+1}: {http_e.detail}")
                    results.append({
                        "question_id": i + 1,
                        "question": question,
                        "success": False,
                        "error": f"RAGAS evaluation HTTP error: {http_e.detail[:200]}"
                    })
                except Exception as ragas_error:
                    logger.error(f"RAGAS evaluation failed for question {i+1}: {ragas_error}")
                    import traceback
                    logger.error(f"Traceback: {traceback.format_exc()}")
                    results.append({
                        "question_id": i + 1,
                        "question": question,
                        "success": False,
                        "error": f"RAGAS evaluation error: {str(ragas_error)[:200]}"
                    })
                
            except Exception as e:
                logger.error(f"Failed to evaluate question {i+1}: {e}")
                results.append({
                    "question_id": i + 1,
                    "question": question,
                    "success": False,
                    "error": str(e)
                })
        
        # Calculate aggregate metrics
        successful_results = [r for r in results if r.get("success")]
        if successful_results:
            avg_faithfulness = sum(r["ragas_metrics"]["faithfulness"] for r in successful_results) / len(successful_results)
            avg_answer_relevancy = sum(r["ragas_metrics"]["answer_relevancy"] for r in successful_results) / len(successful_results)
            avg_overall = sum(r["ragas_metrics"]["overall_score"] for r in successful_results) / len(successful_results)
            
            context_results = [r for r in successful_results if r["ragas_metrics"].get("context_precision") is not None]
            avg_context_precision = None
            avg_context_recall = None
            if context_results:
                avg_context_precision = sum(r["ragas_metrics"]["context_precision"] for r in context_results) / len(context_results)
                avg_context_recall = sum(r["ragas_metrics"]["context_recall"] for r in context_results) / len(context_results)
            
            aggregate_metrics = {
                "average_faithfulness": avg_faithfulness,
                "average_answer_relevancy": avg_answer_relevancy,
                "average_context_precision": avg_context_precision,
                "average_context_recall": avg_context_recall,
                "average_overall_score": avg_overall
            }
        else:
            aggregate_metrics = {}
        
        # Update test data
        test_data["status"] = "completed"
        test_data["progress"] = 100.0
        test_data["end_time"] = datetime.utcnow().isoformat()
        test_data["results"] = results
        test_data["aggregate_metrics"] = aggregate_metrics
        test_data["total_questions"] = total_questions
        test_data["successful_questions"] = len(successful_results)
        test_data["failed_questions"] = total_questions - len(successful_results)
        
        RAGAS_TEST_STORAGE[test_id] = test_data
        _save_ragas_test_to_db(test_id, test_data)
        
        logger.info(f"Batch evaluation completed for test {test_id}")
        
    except Exception as e:
        logger.error(f"Batch evaluation failed: {e}", exc_info=True)
        test_data = RAGAS_TEST_STORAGE.get(test_id)
        if test_data:
            test_data["status"] = "failed"
            test_data["error"] = str(e)
            _save_ragas_test_to_db(test_id, test_data)


@router.post("/start", summary="Start RAGAS Batch Evaluation")
async def start_ragas_batch_evaluation(
    request: RAGASBatchStartRequest,
    background_tasks: BackgroundTasks,
    http_request: Request
) -> Dict[str, Any]:
    """
    Start batch RAGAS evaluation with multiple questions
    
    Similar to test-simulation, but uses RAGAS metrics instead of cosine similarity.
    Can use production data from session or provided questions.
    """
    from src.api.main import _require_owner_or_admin
    
    # Verify access to session
    _require_owner_or_admin(http_request, request.sessionId)
    
    try:
        # Generate unique test ID
        test_id = str(uuid.uuid4())
        
        # Get questions (from production or provided)
        if request.useProductionData:
            # TODO: Fetch production queries from session
            # For now, use provided questions
            questions = request.questions
            if request.maxQuestions:
                questions = questions[:request.maxQuestions]
        else:
            questions = request.questions
        
        if not questions:
            raise HTTPException(status_code=400, detail="No questions provided")
        
        # Initialize test data
        test_data = {
            "test_id": test_id,
            "test_name": request.testName,
            "session_id": request.sessionId,
            "session_settings": request.sessionSettings,
            "status": "running",
            "current_question": 0,
            "total_questions": len(questions),
            "progress": 0.0,
            "start_time": datetime.utcnow().isoformat(),
            "end_time": None,
            "questions": questions,
            "expected_answers": request.expectedAnswers or {},
            "results": [],
            "aggregate_metrics": {}
        }
        
        # Store test data
        RAGAS_TEST_STORAGE[test_id] = test_data
        _save_ragas_test_to_db(test_id, test_data)
        
        # Start background task
        background_tasks.add_task(
            execute_ragas_batch_evaluation,
            test_id,
            questions,
            request.sessionId,
            request.sessionSettings,
            request.expectedAnswers or {}
        )
        
        return {
            "success": True,
            "testId": test_id,
            "message": "RAGAS batch evaluation started",
            "total_questions": len(questions),
            "estimated_duration_minutes": len(questions) * 0.5  # ~30 seconds per question
        }
        
    except Exception as e:
        logger.error(f"Failed to start RAGAS batch evaluation: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to start evaluation: {str(e)}")


@router.get("/status/{test_id}", summary="Get RAGAS Batch Evaluation Status")
async def get_ragas_batch_status(test_id: str, http_request: Request) -> Dict[str, Any]:
    """Get status and results of RAGAS batch evaluation"""
    from src.api.main import _require_owner_or_admin
    
    try:
        # Load test data
        test_data = RAGAS_TEST_STORAGE.get(test_id)
        if not test_data:
            test_data = _load_ragas_test_from_db(test_id)
            if not test_data:
                raise HTTPException(status_code=404, detail="Test not found")
            RAGAS_TEST_STORAGE[test_id] = test_data
        
        # Verify access
        _require_owner_or_admin(http_request, test_data.get("session_id", ""))
        
        # Calculate progress
        total = test_data.get("total_questions", 0)
        current = test_data.get("current_question", 0)
        progress = (current / total * 100) if total > 0 else 0.0
        
        # Calculate execution time
        start_time = test_data.get("start_time")
        end_time = test_data.get("end_time")
        execution_time = None
        if start_time:
            start_dt = datetime.fromisoformat(start_time.replace('Z', '+00:00'))
            if end_time:
                end_dt = datetime.fromisoformat(end_time.replace('Z', '+00:00'))
                elapsed = (end_dt - start_dt).total_seconds()
                execution_time = {
                    "total_seconds": elapsed,
                    "total_minutes": elapsed / 60,
                    "formatted": f"{int(elapsed // 60)}m {int(elapsed % 60)}s"
                }
            else:
                elapsed = (datetime.utcnow() - start_dt.replace(tzinfo=None)).total_seconds()
                execution_time = {
                    "elapsed_seconds": elapsed,
                    "elapsed_minutes": elapsed / 60,
                    "status": "running"
                }
        
        return {
            "success": True,
            "testId": test_id,
            "testName": test_data.get("test_name", ""),
            "status": test_data.get("status", "unknown"),
            "progress": round(progress, 1),
            "current_question": current,
            "total_questions": total,
            "startTime": start_time,
            "endTime": end_time,
            "executionTime": execution_time,
            "aggregate_metrics": test_data.get("aggregate_metrics", {}),
            "results": test_data.get("results", []),
            "successful_questions": test_data.get("successful_questions", 0),
            "failed_questions": test_data.get("failed_questions", 0)
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to get RAGAS batch status: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to get status: {str(e)}")


@router.get("/list", summary="List All RAGAS Tests")
async def list_ragas_tests(http_request: Request, session_id: Optional[str] = None) -> Dict[str, Any]:
    """List all RAGAS test results"""
    try:
        with sqlite3.connect(RAGAS_TEST_DB_PATH) as conn:
            if session_id:
                cursor = conn.execute("""
                    SELECT test_id, data, created_at, updated_at 
                    FROM ragas_test_results 
                    WHERE json_extract(data, '$.session_id') = ?
                    ORDER BY updated_at DESC
                """, (session_id,))
            else:
                cursor = conn.execute("""
                    SELECT test_id, data, created_at, updated_at 
                    FROM ragas_test_results 
                    ORDER BY updated_at DESC
                """)
            
            rows = cursor.fetchall()
            tests = []
            for row in rows:
                test_id, data_json, created_at, updated_at = row
                try:
                    test_data = json.loads(data_json)
                    tests.append({
                        "testId": test_id,
                        "testName": test_data.get("test_name", f"Test {test_id[:8]}"),
                        "status": test_data.get("status", "unknown"),
                        "sessionId": test_data.get("session_id", ""),
                        "startTime": test_data.get("start_time"),
                        "endTime": test_data.get("end_time"),
                        "createdAt": created_at,
                        "updatedAt": updated_at,
                        "totalQuestions": test_data.get("total_questions", 0),
                        "progress": test_data.get("progress", 0)
                    })
                except json.JSONDecodeError:
                    continue
            
            return {
                "success": True,
                "tests": tests,
                "total": len(tests)
            }
    except Exception as e:
        logger.error(f"Failed to list RAGAS tests: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to list tests: {str(e)}")


@router.post("/evaluate-batch")
async def evaluate_rag_batch(requests: List[RAGASEvaluationRequest]):
    """
    Evaluate multiple RAG queries in batch
    
    This endpoint evaluates multiple question-answer pairs and returns
    aggregated metrics.
    """
    try:
        logger.info(f"Evaluating batch of {len(requests)} RAG queries")
        
        results = []
        for i, req in enumerate(requests):
            try:
                # Use the single evaluation endpoint
                result = await evaluate_rag(req)
                results.append({
                    "index": i,
                    "question": req.question,
                    "result": result.dict(),
                    "success": True
                })
            except Exception as e:
                logger.error(f"Failed to evaluate query {i}: {e}")
                results.append({
                    "index": i,
                    "question": req.question,
                    "error": str(e),
                    "success": False
                })
        
        # Calculate aggregate metrics
        successful_results = [r for r in results if r.get("success")]
        if successful_results:
            avg_faithfulness = sum(r["result"]["faithfulness"] for r in successful_results) / len(successful_results)
            avg_answer_relevancy = sum(r["result"]["answer_relevancy"] for r in successful_results) / len(successful_results)
            avg_overall = sum(r["result"]["overall_score"] for r in successful_results) / len(successful_results)
            
            # Calculate context metrics if available
            context_results = [r for r in successful_results if r["result"].get("context_precision") is not None]
            avg_context_precision = None
            avg_context_recall = None
            if context_results:
                avg_context_precision = sum(r["result"]["context_precision"] for r in context_results) / len(context_results)
                avg_context_recall = sum(r["result"]["context_recall"] for r in context_results) / len(context_results)
            
            return {
                "total_queries": len(requests),
                "successful": len(successful_results),
                "failed": len(requests) - len(successful_results),
                "aggregate_metrics": {
                    "average_faithfulness": avg_faithfulness,
                    "average_answer_relevancy": avg_answer_relevancy,
                    "average_context_precision": avg_context_precision,
                    "average_context_recall": avg_context_recall,
                    "average_overall_score": avg_overall
                },
                "results": results
            }
        else:
            return {
                "total_queries": len(requests),
                "successful": 0,
                "failed": len(requests),
                "error": "All evaluations failed",
                "results": results
            }
            
    except Exception as e:
        logger.error(f"Batch evaluation error: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Batch evaluation failed: {str(e)}"
        )

