"""
RAGAS Evaluation Routes

Provides endpoints for RAG evaluation using RAGAS metrics:
- Faithfulness: Measures if the answer is grounded in the given context
- Answer Relevancy: Measures how relevant the answer is to the question
- Context Precision: Measures the precision of the retrieved context
- Context Recall: Measures the recall of the retrieved context

Batch Evaluation:
- Start batch evaluation with multiple questions
- Track progress and status
- Collect production data automatically
- Compare different methodologies
"""

import logging
import os
import uuid
import asyncio
import json
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Dict, Any
from fastapi import APIRouter, HTTPException, BackgroundTasks, Request
from fastapi.responses import Response, StreamingResponse
from pydantic import BaseModel, Field
import requests
import httpx
from io import BytesIO
try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    logger.warning("reportlab not available - PDF export will be disabled")

logger = logging.getLogger(__name__)

# RAGAS Service URL
RAGAS_SERVICE_URL = os.getenv(
    'RAGAS_SERVICE_URL',
    os.getenv('RAGAS_SERVICE_HOST', 'http://ragas-service:8010')
)
# Ensure we have the full URL
if not RAGAS_SERVICE_URL.startswith('http'):
    RAGAS_SERVICE_PORT = os.getenv('RAGAS_SERVICE_PORT', '8010')
    RAGAS_SERVICE_URL = f'http://{RAGAS_SERVICE_URL}:{RAGAS_SERVICE_PORT}'

# API Gateway URL (for getting RAG responses)
API_GATEWAY_URL = os.getenv('API_GATEWAY_URL', os.getenv('API_GATEWAY_INTERNAL_URL', 'http://localhost:8000'))
if API_GATEWAY_URL.startswith('https://'):
    API_GATEWAY_URL = API_GATEWAY_URL.replace('https://', 'http://')

router = APIRouter(prefix="/rag-metrics", tags=["RAG Metrics (RAGAS)"])

# Test results storage (similar to test_simulation_routes)
RAGAS_TEST_STORAGE: Dict[str, Any] = {}

# Database for RAGAS test persistence
RAGAS_TEST_DB_PATH = Path("data/ragas_test_results.db")

def _init_ragas_test_db():
    """Initialize RAGAS test results database"""
    RAGAS_TEST_DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with sqlite3.connect(RAGAS_TEST_DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS ragas_test_results (
                test_id TEXT PRIMARY KEY,
                data TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

def _save_ragas_test_to_db(test_id: str, test_data: Dict[str, Any]):
    """Save RAGAS test data to database and update memory"""
    try:
        with sqlite3.connect(RAGAS_TEST_DB_PATH) as conn:
            conn.execute("""
                INSERT OR REPLACE INTO ragas_test_results (test_id, data, updated_at)
                VALUES (?, ?, CURRENT_TIMESTAMP)
            """, (test_id, json.dumps(test_data)))
        
        # CRITICAL: Always update memory after saving to DB to prevent cache issues
        # This ensures memory and DB stay in sync
        RAGAS_TEST_STORAGE[test_id] = test_data.copy()  # Use copy to avoid reference issues
        logger.debug(f"💾 Saved test {test_id} to DB and updated memory")
    except Exception as e:
        logger.warning(f"Failed to save RAGAS test to DB: {e}")

def _load_ragas_test_from_db(test_id: str) -> Optional[Dict[str, Any]]:
    """Load RAGAS test data from database"""
    try:
        with sqlite3.connect(RAGAS_TEST_DB_PATH) as conn:
            cursor = conn.execute("SELECT data FROM ragas_test_results WHERE test_id = ?", (test_id,))
            row = cursor.fetchone()
            if row:
                return json.loads(row[0])
    except Exception as e:
        logger.warning(f"Failed to load RAGAS test from DB: {e}")
    return None

# Initialize database on startup
_init_ragas_test_db()


class RAGASEvaluationRequest(BaseModel):
    """Request model for RAGAS evaluation"""
    question: str = Field(..., description="The question being asked")
    answer: str = Field(..., description="The answer generated by the RAG system")
    contexts: List[str] = Field(..., description="List of context documents used to generate the answer")
    ground_truth: Optional[str] = Field(None, description="Optional ground truth answer for context precision/recall")


class RAGASEvaluationResponse(BaseModel):
    """Response model for RAGAS evaluation"""
    faithfulness: float = Field(..., description="Faithfulness score (0-1)")
    answer_relevancy: float = Field(..., description="Answer relevancy score (0-1)")
    context_precision: Optional[float] = Field(None, description="Context precision score (0-1), requires ground_truth")
    context_recall: Optional[float] = Field(None, description="Context recall score (0-1), requires ground_truth")
    overall_score: float = Field(..., description="Overall average score")
    metrics_available: List[str] = Field(..., description="List of metrics that were calculated")


# Batch Evaluation Models (similar to test-simulation)
class RAGASBatchStartRequest(BaseModel):
    """Request model for starting RAGAS batch evaluation"""
    testName: str = Field(..., description="Name of the test")
    questions: List[str] = Field(..., description="List of questions to test")
    sessionId: str = Field(..., description="Session ID for testing")
    sessionSettings: Optional[Dict[str, Any]] = Field(default=None, description="Session RAG settings")
    expectedAnswers: Optional[Dict[int, str]] = Field(default=None, description="Optional map of question index to expected answer (ground truth)")
    useProductionData: bool = Field(default=False, description="Use production queries from session instead of provided questions")
    maxQuestions: Optional[int] = Field(default=None, description="Maximum number of questions to use from production data")


class RAGASQuestionResult(BaseModel):
    """Result for a single question evaluation"""
    question_id: int
    question: str
    answer: str
    contexts: List[str]
    ground_truth: Optional[str]
    ragas_metrics: RAGASEvaluationResponse
    response_time_ms: float
    retrieval_count: int


@router.get("/health")
async def health_check():
    """Health check endpoint"""
    try:
        # Check if RAGAS service is available
        async with httpx.AsyncClient(timeout=5.0) as client:
            response = await client.get(f"{RAGAS_SERVICE_URL}/health")
            if response.status_code == 200:
                return {
                    "status": "healthy",
                    "ragas_service": "available",
                    "ragas_service_url": RAGAS_SERVICE_URL
                }
            else:
                return {
                    "status": "degraded",
                    "ragas_service": "unavailable",
                    "ragas_service_url": RAGAS_SERVICE_URL,
                    "error": f"RAGAS service returned status {response.status_code}"
                }
    except Exception as e:
        logger.error(f"Health check failed: {e}")
        return {
            "status": "unhealthy",
            "ragas_service": "unavailable",
            "ragas_service_url": RAGAS_SERVICE_URL,
            "error": str(e)
        }


@router.post("/evaluate", response_model=RAGASEvaluationResponse)
async def evaluate_rag(request: RAGASEvaluationRequest):
    """
    Evaluate RAG performance using RAGAS metrics
    
    This endpoint forwards the evaluation request to the RAGAS service
    and returns the calculated metrics.
    """
    try:
        logger.info(f"Evaluating RAG performance for question: {request.question[:50]}...")
        
        # Forward request to RAGAS service
        # Increased timeout to 300 seconds (5 minutes) for RAGAS evaluation
        async with httpx.AsyncClient(timeout=300.0) as client:
            logger.info(f"📡 Sending request to RAGAS service at {RAGAS_SERVICE_URL}/evaluate")
            logger.debug(f"   Question: {request.question[:50]}...")
            logger.debug(f"   Answer length: {len(request.answer)} chars")
            logger.debug(f"   Contexts count: {len(request.contexts)}")
            logger.debug(f"   Ground truth: {'Yes' if request.ground_truth else 'No'}")
            
            response = await client.post(
                f"{RAGAS_SERVICE_URL}/evaluate",
                json={
                    "question": request.question,
                    "answer": request.answer,
                    "contexts": request.contexts,
                    "ground_truth": request.ground_truth
                }
            )
            
            logger.info(f"📥 RAGAS service response: {response.status_code}")
            
            if response.status_code != 200:
                try:
                    error_text = await response.aread()
                    error_str = error_text.decode() if error_text else "Unknown error"
                    logger.error(f"❌ RAGAS service error: {response.status_code} - {error_str[:500]}")
                    raise HTTPException(
                        status_code=response.status_code,
                        detail=f"RAGAS service error: {error_str[:500]}"
                    )
                except Exception as e:
                    logger.error(f"❌ Failed to read error response: {e}")
                    raise HTTPException(
                        status_code=response.status_code,
                        detail=f"RAGAS service returned status {response.status_code}"
                    )
            
            # Parse response with better error handling
            try:
                response_text = await response.aread()
                if not response_text:
                    logger.error("❌ RAGAS service returned empty response")
                    raise HTTPException(
                        status_code=502,
                        detail="RAGAS service returned empty response"
                    )
                
                result = json.loads(response_text.decode())
                logger.info(f"✅ RAGAS response parsed successfully")
                logger.debug(f"   Result keys: {list(result.keys())}")
                
            except json.JSONDecodeError as e:
                logger.error(f"❌ Failed to parse RAGAS response as JSON: {e}")
                logger.error(f"   Response text (first 500 chars): {response_text.decode()[:500] if response_text else 'None'}")
                raise HTTPException(
                    status_code=502,
                    detail=f"RAGAS service returned invalid JSON: {str(e)[:200]}"
                )
            except Exception as e:
                logger.error(f"❌ Error reading RAGAS response: {e}")
                raise HTTPException(
                    status_code=502,
                    detail=f"Failed to read RAGAS service response: {str(e)[:200]}"
                )
            
            # Validate response has required fields
            if not isinstance(result, dict):
                logger.error(f"❌ RAGAS response is not a dictionary: {type(result)}")
                raise HTTPException(
                    status_code=502,
                    detail="RAGAS service returned invalid response format"
                )
            
            # Determine which metrics were calculated
            metrics_available = ["faithfulness", "answer_relevancy"]
            if request.ground_truth:
                metrics_available.extend(["context_precision", "context_recall"])
            
            # Extract metrics with validation
            # Handle NaN values from RAGAS (they come as None or NaN in JSON)
            def safe_float(value, default=0.0):
                """Safely convert value to float, handling None and NaN"""
                if value is None:
                    return default
                try:
                    fval = float(value)
                    import math
                    if math.isnan(fval):
                        return default
                    return fval
                except (ValueError, TypeError):
                    return default
            
            faithfulness = safe_float(result.get("faithfulness"), 0.0)
            answer_relevancy = safe_float(result.get("answer_relevancy"), 0.0)
            overall_score = safe_float(result.get("overall_score"), 0.0)
            context_precision = result.get("context_precision")
            context_recall = result.get("context_recall")
            
            # Convert optional metrics safely
            if context_precision is not None:
                context_precision = safe_float(context_precision, None)
            if context_recall is not None:
                context_recall = safe_float(context_recall, None)
            
            # Log extracted metrics
            logger.info(f"📊 Extracted metrics from RAGAS service:")
            logger.info(f"   Faithfulness: {faithfulness}")
            logger.info(f"   Answer Relevancy: {answer_relevancy}")
            logger.info(f"   Context Precision: {context_precision}")
            logger.info(f"   Context Recall: {context_recall}")
            logger.info(f"   Overall Score: {overall_score}")
            logger.info(f"   Full result keys: {list(result.keys())}")
            
            # Even if some metrics are 0.0 (failed), we still return the response
            # The frontend can handle partial results
            response = RAGASEvaluationResponse(
                faithfulness=faithfulness,
                answer_relevancy=answer_relevancy,
                context_precision=context_precision,
                context_recall=context_recall,
                overall_score=overall_score,
                metrics_available=metrics_available
            )
            
            logger.info(f"✅ Returning RAGAS evaluation response to client")
            logger.debug(f"   Response: {response.model_dump()}")
            
            return response
            
    except httpx.TimeoutException:
        logger.error("RAGAS service timeout")
        raise HTTPException(
            status_code=504,
            detail="RAGAS service request timed out. The evaluation may take longer than expected."
        )
    except httpx.ConnectError:
        logger.error(f"Could not connect to RAGAS service at {RAGAS_SERVICE_URL}")
        raise HTTPException(
            status_code=503,
            detail=f"RAGAS service is unavailable at {RAGAS_SERVICE_URL}. Please check if the service is running."
        )
    except Exception as e:
        logger.error(f"Evaluation error: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Evaluation failed: {str(e)}"
        )


# Helper function to execute RAG query and get response with contexts
async def execute_rag_query(session_id: str, question: str, session_settings: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Execute RAG query and return answer with contexts (similar to test-simulation)"""
    import time
    start_time = time.time()
    
    try:
        # Use API Gateway's /rag/query endpoint (same as test-simulation)
        async with httpx.AsyncClient(timeout=120.0, verify=False) as client:
            response = await client.post(
                f"{API_GATEWAY_URL}/rag/query",
                json={
                    "session_id": session_id,
                    "query": question,
                    "top_k": 5,
                    "use_rerank": True,
                    "min_score": 0.1,
                    "max_context_chars": 8000,
                    "use_direct_llm": False,
                    "disable_aprag": True,  # Disable personalization for consistent evaluation
                    "use_crag": False,
                    "session_settings": session_settings
                }
            )
            
            execution_time = (time.time() - start_time) * 1000
            
            if response.status_code == 200:
                try:
                    result = response.json()
                    
                    # Validate response structure
                    if not isinstance(result, dict):
                        logger.error(f"RAG query returned non-dict response: {type(result)}")
                        return {
                            "success": False,
                            "error": "Invalid response format from RAG service",
                            "answer": "",
                            "contexts": [],
                            "sources": [],
                            "response_time_ms": execution_time
                        }
                    
                    # Extract answer and contexts
                    answer = result.get("answer", "")
                    sources = result.get("sources", [])
                    contexts = []
                    
                    if not sources:
                        logger.warning(f"No sources returned from RAG query")
                    
                    for source in sources:
                        if isinstance(source, dict):
                            content = source.get("content") or source.get("chunk_text") or source.get("text", "")
                            if content:
                                contexts.append(content)
                        elif isinstance(source, str):
                            contexts.append(source)
                    
                    if not answer:
                        logger.warning(f"Empty answer returned from RAG query")
                    
                    logger.info(f"✅ RAG query successful: answer_length={len(answer)}, contexts_count={len(contexts)}")
                    
                    return {
                        "success": True,
                        "answer": answer,
                        "contexts": contexts,
                        "sources": sources,
                        "response_time_ms": execution_time
                    }
                except json.JSONDecodeError as e:
                    logger.error(f"Failed to parse RAG response as JSON: {e}")
                    return {
                        "success": False,
                        "error": f"Failed to parse RAG response: {str(e)[:200]}",
                        "answer": "",
                        "contexts": [],
                        "sources": [],
                        "response_time_ms": execution_time
                    }
            else:
                try:
                    error_text = await response.aread()
                    error_str = error_text.decode()[:500] if error_text else f"HTTP {response.status_code}"
                    logger.error(f"RAG query failed: {response.status_code} - {error_str}")
                    return {
                        "success": False,
                        "error": f"API Error: {response.status_code} - {error_str}",
                        "answer": "",
                        "contexts": [],
                        "sources": [],
                        "response_time_ms": execution_time
                    }
                except Exception as e:
                    logger.error(f"Failed to read error response: {e}")
                    return {
                        "success": False,
                        "error": f"API Error: {response.status_code} - Failed to read error message",
                        "answer": "",
                        "contexts": [],
                        "sources": [],
                        "response_time_ms": execution_time
                    }
    except Exception as e:
        execution_time = (time.time() - start_time) * 1000
        logger.error(f"Failed to execute RAG query: {e}")
        return {
            "success": False,
            "error": str(e),
            "answer": "",
            "contexts": [],
            "sources": [],
            "response_time_ms": execution_time
        }


# Background task for batch evaluation
async def execute_ragas_batch_evaluation(
    test_id: str,
    questions: List[str],
    session_id: str,
    session_settings: Optional[Dict[str, Any]],
    expected_answers: Optional[Dict[int, str]]
):
    """Execute batch RAGAS evaluation in background"""
    try:
        test_data = RAGAS_TEST_STORAGE.get(test_id)
        if not test_data:
            test_data = _load_ragas_test_from_db(test_id)
            if not test_data:
                logger.error(f"Test {test_id} not found")
                return
            RAGAS_TEST_STORAGE[test_id] = test_data
        
        # CRITICAL: Always work with memory reference, not DB copy
        # This ensures all updates go to the same object
        test_data["status"] = "running"
        test_data["current_question"] = 0
        test_data["total_questions"] = len(questions)
        test_data["results"] = []
        
        # Save to DB (which will also update memory via _save_ragas_test_to_db)
        _save_ragas_test_to_db(test_id, test_data)
        
        results = []
        total_questions = len(questions)
        
        for i, question in enumerate(questions):
            try:
                test_data["current_question"] = i + 1
                progress = ((i + 1) / total_questions) * 100
                test_data["progress"] = round(progress, 1)
                _save_ragas_test_to_db(test_id, test_data)
                
                logger.info(f"Processing question {i+1}/{total_questions}: {question[:50]}...")
                
                # Execute RAG query
                rag_result = await execute_rag_query(session_id, question, session_settings)
                
                if not rag_result["success"]:
                    logger.error(f"RAG query failed for question {i+1}")
                    results.append({
                        "question_id": i + 1,
                        "question": question,
                        "success": False,
                        "error": rag_result.get("error", "RAG query failed")
                    })
                    continue
                
                # Get ground truth if available
                ground_truth = expected_answers.get(i) if expected_answers else None
                
                # Validate RAG result before evaluation
                if not rag_result.get("answer"):
                    logger.warning(f"Question {i+1} has empty answer, skipping RAGAS evaluation")
                    results.append({
                        "question_id": i + 1,
                        "question": question,
                        "success": False,
                        "error": "Empty answer from RAG query"
                    })
                    continue
                
                if not rag_result.get("contexts"):
                    logger.warning(f"Question {i+1} has no contexts, RAGAS evaluation may be limited")
                
                # Evaluate with RAGAS
                try:
                    ragas_request = RAGASEvaluationRequest(
                        question=question,
                        answer=rag_result["answer"],
                        contexts=rag_result["contexts"] or [""],  # Ensure at least empty list
                        ground_truth=ground_truth
                    )
                    
                    logger.info(f"Evaluating question {i+1} with RAGAS...")
                    ragas_result = await evaluate_rag(ragas_request)
                    
                    # Validate RAGAS result
                    if not ragas_result:
                        logger.error(f"RAGAS returned empty result for question {i+1}")
                        results.append({
                            "question_id": i + 1,
                            "question": question,
                            "success": False,
                            "error": "RAGAS evaluation returned empty result"
                        })
                        continue
                    
                    # Convert to dict safely - Pydantic v2 uses model_dump() instead of dict()
                    if hasattr(ragas_result, 'model_dump'):
                        # Pydantic v2
                        ragas_metrics = ragas_result.model_dump()
                    elif hasattr(ragas_result, 'dict'):
                        # Pydantic v1 fallback
                        ragas_metrics = ragas_result.dict()
                    elif isinstance(ragas_result, dict):
                        # Already a dict
                        ragas_metrics = ragas_result
                    else:
                        # Last resort: try to convert to dict via JSON
                        try:
                            import json
                            # Use model_dump_json if available, otherwise try dict()
                            if hasattr(ragas_result, 'model_dump_json'):
                                ragas_metrics = json.loads(ragas_result.model_dump_json())
                            else:
                                ragas_metrics = json.loads(json.dumps(ragas_result, default=str))
                        except Exception as e:
                            logger.error(f"Failed to convert RAGAS result to dict: {e}")
                            # Fallback to empty metrics
                            ragas_metrics = {
                                "faithfulness": 0.0,
                                "answer_relevancy": 0.0,
                                "context_precision": None,
                                "context_recall": None,
                                "overall_score": 0.0,
                                "metrics_available": []
                            }
                    
                    logger.info(f"✅ Question {i+1} evaluated successfully: faithfulness={ragas_metrics.get('faithfulness')}, answer_relevancy={ragas_metrics.get('answer_relevancy')}")
                    logger.debug(f"   RAGAS metrics type: {type(ragas_metrics)}, keys: {list(ragas_metrics.keys()) if isinstance(ragas_metrics, dict) else 'N/A'}")
                    
                    result_entry = {
                        "question_id": i + 1,
                        "question": question,
                        "answer": rag_result["answer"],
                        "contexts": rag_result["contexts"],
                        "ground_truth": ground_truth,
                        "ragas_metrics": ragas_metrics,
                        "response_time_ms": rag_result["response_time_ms"],
                        "retrieval_count": len(rag_result["contexts"]),
                        "success": True
                    }
                    
                    # Validate ragas_metrics is serializable
                    try:
                        import json
                        json.dumps(result_entry)  # Test serialization
                        logger.debug(f"   Result entry is JSON serializable")
                    except Exception as ser_error:
                        logger.error(f"   ⚠️ Result entry is NOT JSON serializable: {ser_error}")
                        logger.error(f"   ragas_metrics type: {type(ragas_metrics)}")
                        # Try to fix it
                        if not isinstance(ragas_metrics, dict):
                            logger.warning(f"   Converting ragas_metrics to dict...")
                            ragas_metrics = {"error": "Failed to serialize metrics"}
                            result_entry["ragas_metrics"] = ragas_metrics
                    
                    results.append(result_entry)
                    
                    # Update test_data with current results in real-time
                    test_data["results"] = results
                    successful_count = len([r for r in results if r.get("success")])
                    test_data["successful_questions"] = successful_count
                    test_data["failed_questions"] = i + 1 - successful_count
                    
                    # Calculate aggregate metrics incrementally (for real-time display)
                    successful_results = [r for r in results if r.get("success")]
                    if successful_results:
                        # Safe sum with None handling - filter out None values
                        faithfulness_values = [r["ragas_metrics"].get("faithfulness") for r in successful_results if r["ragas_metrics"].get("faithfulness") is not None]
                        answer_relevancy_values = [r["ragas_metrics"].get("answer_relevancy") for r in successful_results if r["ragas_metrics"].get("answer_relevancy") is not None]
                        overall_values = [r["ragas_metrics"].get("overall_score") for r in successful_results if r["ragas_metrics"].get("overall_score") is not None]
                        
                        avg_faithfulness = sum(faithfulness_values) / len(faithfulness_values) if faithfulness_values else 0.0
                        avg_answer_relevancy = sum(answer_relevancy_values) / len(answer_relevancy_values) if answer_relevancy_values else 0.0
                        avg_overall = sum(overall_values) / len(overall_values) if overall_values else 0.0
                        
                        # Context metrics (optional - may be None)
                        context_results = [r for r in successful_results if r["ragas_metrics"].get("context_precision") is not None]
                        avg_context_precision = None
                        avg_context_recall = None
                        if context_results:
                            context_precision_values = [r["ragas_metrics"]["context_precision"] for r in context_results if r["ragas_metrics"].get("context_precision") is not None]
                            context_recall_values = [r["ragas_metrics"]["context_recall"] for r in context_results if r["ragas_metrics"].get("context_recall") is not None]
                            avg_context_precision = sum(context_precision_values) / len(context_precision_values) if context_precision_values else None
                            avg_context_recall = sum(context_recall_values) / len(context_recall_values) if context_recall_values else None
                        
                        test_data["aggregate_metrics"] = {
                            "average_faithfulness": avg_faithfulness,
                            "average_answer_relevancy": avg_answer_relevancy,
                            "average_context_precision": avg_context_precision,
                            "average_context_recall": avg_context_recall,
                            "average_overall_score": avg_overall
                        }
                    else:
                        test_data["aggregate_metrics"] = {}
                    
                    # Save to DB after each question for real-time updates
                    _save_ragas_test_to_db(test_id, test_data)
                    logger.info(f"💾 Saved progress: {i+1}/{total_questions} questions, {successful_count} successful")
                    
                except HTTPException as http_e:
                    logger.error(f"HTTP error evaluating question {i+1}: {http_e.detail}")
                    error_result = {
                        "question_id": i + 1,
                        "question": question,
                        "success": False,
                        "error": f"RAGAS evaluation HTTP error: {http_e.detail[:200]}"
                    }
                    results.append(error_result)
                    
                    # Update test_data with current results
                    test_data["results"] = results
                    successful_count = len([r for r in results if r.get("success")])
                    test_data["successful_questions"] = successful_count
                    test_data["failed_questions"] = i + 1 - successful_count
                    _save_ragas_test_to_db(test_id, test_data)
                    
                except Exception as ragas_error:
                    logger.error(f"RAGAS evaluation failed for question {i+1}: {ragas_error}")
                    import traceback
                    logger.error(f"Traceback: {traceback.format_exc()}")
                    error_result = {
                        "question_id": i + 1,
                        "question": question,
                        "success": False,
                        "error": f"RAGAS evaluation error: {str(ragas_error)[:200]}"
                    }
                    results.append(error_result)
                    
                    # Update test_data with current results
                    test_data["results"] = results
                    successful_count = len([r for r in results if r.get("success")])
                    test_data["successful_questions"] = successful_count
                    test_data["failed_questions"] = i + 1 - successful_count
                    _save_ragas_test_to_db(test_id, test_data)
                
            except Exception as e:
                logger.error(f"Failed to evaluate question {i+1}: {e}")
                error_result = {
                    "question_id": i + 1,
                    "question": question,
                    "success": False,
                    "error": str(e)
                }
                results.append(error_result)
                
                # Update test_data with current results
                test_data["results"] = results
                successful_count = len([r for r in results if r.get("success")])
                test_data["successful_questions"] = successful_count
                test_data["failed_questions"] = i + 1 - successful_count
                _save_ragas_test_to_db(test_id, test_data)
        
        # Calculate aggregate metrics (final calculation)
        successful_results = [r for r in results if r.get("success")]
        if successful_results:
            # Safe sum with None handling - filter out None values
            faithfulness_values = [r["ragas_metrics"].get("faithfulness") for r in successful_results if r["ragas_metrics"].get("faithfulness") is not None]
            answer_relevancy_values = [r["ragas_metrics"].get("answer_relevancy") for r in successful_results if r["ragas_metrics"].get("answer_relevancy") is not None]
            overall_values = [r["ragas_metrics"].get("overall_score") for r in successful_results if r["ragas_metrics"].get("overall_score") is not None]
            
            avg_faithfulness = sum(faithfulness_values) / len(faithfulness_values) if faithfulness_values else 0.0
            avg_answer_relevancy = sum(answer_relevancy_values) / len(answer_relevancy_values) if answer_relevancy_values else 0.0
            avg_overall = sum(overall_values) / len(overall_values) if overall_values else 0.0
            
            # Context metrics (optional - may be None)
            context_results = [r for r in successful_results if r["ragas_metrics"].get("context_precision") is not None]
            avg_context_precision = None
            avg_context_recall = None
            if context_results:
                context_precision_values = [r["ragas_metrics"]["context_precision"] for r in context_results if r["ragas_metrics"].get("context_precision") is not None]
                context_recall_values = [r["ragas_metrics"]["context_recall"] for r in context_results if r["ragas_metrics"].get("context_recall") is not None]
                avg_context_precision = sum(context_precision_values) / len(context_precision_values) if context_precision_values else None
                avg_context_recall = sum(context_recall_values) / len(context_recall_values) if context_recall_values else None
            
            aggregate_metrics = {
                "average_faithfulness": avg_faithfulness,
                "average_answer_relevancy": avg_answer_relevancy,
                "average_context_precision": avg_context_precision,
                "average_context_recall": avg_context_recall,
                "average_overall_score": avg_overall
            }
        else:
            aggregate_metrics = {}
        
        # Update test data - ALWAYS set status to "completed" if we reach here
        # Even if some questions failed, the test itself completed successfully
        test_data["status"] = "completed"
        test_data["progress"] = 100.0
        test_data["end_time"] = datetime.utcnow().isoformat()
        test_data["results"] = results
        test_data["aggregate_metrics"] = aggregate_metrics
        test_data["total_questions"] = total_questions
        test_data["successful_questions"] = len(successful_results)
        test_data["failed_questions"] = total_questions - len(successful_results)
        
        # CRITICAL: Ensure status is saved as "completed" not "failed"
        RAGAS_TEST_STORAGE[test_id] = test_data
        _save_ragas_test_to_db(test_id, test_data)
        
        logger.info(f"✅ Batch evaluation completed for test {test_id}: {len(successful_results)}/{total_questions} successful")
        
    except Exception as e:
        logger.error(f"❌ Batch evaluation failed: {e}", exc_info=True)
        test_data = RAGAS_TEST_STORAGE.get(test_id)
        if test_data:
            # Only set to "failed" if there was an actual exception
            # Don't set to "failed" if test completed but some questions failed
            test_data["status"] = "failed"
            test_data["error"] = str(e)
            test_data["end_time"] = datetime.utcnow().isoformat()
            _save_ragas_test_to_db(test_id, test_data)
            logger.error(f"   Test {test_id} marked as failed due to exception")


@router.post("/start", summary="Start RAGAS Batch Evaluation")
async def start_ragas_batch_evaluation(
    request: RAGASBatchStartRequest,
    background_tasks: BackgroundTasks,
    http_request: Request
) -> Dict[str, Any]:
    """
    Start batch RAGAS evaluation with multiple questions
    
    Similar to test-simulation, but uses RAGAS metrics instead of cosine similarity.
    Can use production data from session or provided questions.
    """
    from src.api.main import _require_owner_or_admin
    
    # Verify access to session
    _require_owner_or_admin(http_request, request.sessionId)
    
    try:
        # Generate unique test ID
        test_id = str(uuid.uuid4())
        
        # Get questions (from production or provided)
        if request.useProductionData:
            # TODO: Fetch production queries from session
            # For now, use provided questions
            questions = request.questions
            if request.maxQuestions:
                questions = questions[:request.maxQuestions]
        else:
            questions = request.questions
        
        if not questions:
            raise HTTPException(status_code=400, detail="No questions provided")
        
        # Initialize test data
        test_data = {
            "test_id": test_id,
            "test_name": request.testName,
            "session_id": request.sessionId,
            "session_settings": request.sessionSettings,
            "status": "running",
            "current_question": 0,
            "total_questions": len(questions),
            "progress": 0.0,
            "start_time": datetime.utcnow().isoformat(),
            "end_time": None,
            "questions": questions,
            "expected_answers": request.expectedAnswers or {},
            "results": [],
            "aggregate_metrics": {}
        }
        
        # Store test data
        RAGAS_TEST_STORAGE[test_id] = test_data
        _save_ragas_test_to_db(test_id, test_data)
        
        # Start background task
        background_tasks.add_task(
            execute_ragas_batch_evaluation,
            test_id,
            questions,
            request.sessionId,
            request.sessionSettings,
            request.expectedAnswers or {}
        )
        
        return {
            "success": True,
            "testId": test_id,
            "message": "RAGAS batch evaluation started",
            "total_questions": len(questions),
            "estimated_duration_minutes": len(questions) * 0.5  # ~30 seconds per question
        }
        
    except Exception as e:
        logger.error(f"Failed to start RAGAS batch evaluation: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to start evaluation: {str(e)}")


@router.get("/status/{test_id}", summary="Get RAGAS Batch Evaluation Status")
async def get_ragas_batch_status(test_id: str, http_request: Request) -> Dict[str, Any]:
    """Get status and results of RAGAS batch evaluation"""
    from src.api.main import _require_owner_or_admin
    
    try:
        # Load test data - ALWAYS prioritize memory over DB
        # Memory is updated in real-time by background task, DB is just for persistence
        # Loading from DB can cause stale data issues (progress going backwards)
        test_data = RAGAS_TEST_STORAGE.get(test_id)
        if not test_data:
            # Only load from DB if not in memory (first request or server restart)
            test_data = _load_ragas_test_from_db(test_id)
            if not test_data:
                raise HTTPException(status_code=404, detail="Test not found")
            # Store in memory for future requests
            RAGAS_TEST_STORAGE[test_id] = test_data
        # If memory exists, use it directly - it's always more up-to-date
        # Background task updates memory in real-time, DB is just for persistence
        
        # Verify access
        _require_owner_or_admin(http_request, test_data.get("session_id", ""))
        
        # Calculate progress - ensure it never goes backwards
        total = test_data.get("total_questions", 0)
        current = test_data.get("current_question", 0)
        results_count = len(test_data.get("results", []))
        
        # Use the maximum of current_question and results_count to prevent backwards progress
        # This handles cases where current_question might be temporarily lower
        actual_progress = max(current, results_count)
        progress = (actual_progress / total * 100) if total > 0 else 0.0
        
        # Ensure progress is between 0 and 100
        progress = max(0.0, min(100.0, progress))
        
        logger.debug(f"📊 Status for test {test_id}: current={current}, results={results_count}, progress={progress:.1f}%")
        
        # Calculate execution time
        start_time = test_data.get("start_time")
        end_time = test_data.get("end_time")
        execution_time = None
        if start_time:
            start_dt = datetime.fromisoformat(start_time.replace('Z', '+00:00'))
            if end_time:
                end_dt = datetime.fromisoformat(end_time.replace('Z', '+00:00'))
                elapsed = (end_dt - start_dt).total_seconds()
                execution_time = {
                    "total_seconds": elapsed,
                    "total_minutes": elapsed / 60,
                    "formatted": f"{int(elapsed // 60)}m {int(elapsed % 60)}s"
                }
            else:
                elapsed = (datetime.utcnow() - start_dt.replace(tzinfo=None)).total_seconds()
                execution_time = {
                    "elapsed_seconds": elapsed,
                    "elapsed_minutes": elapsed / 60,
                    "status": "running"
                }
        
        return {
            "success": True,
            "testId": test_id,
            "testName": test_data.get("test_name", ""),
            "status": test_data.get("status", "unknown"),
            "progress": round(progress, 1),
            "current_question": current,
            "total_questions": total,
            "startTime": start_time,
            "endTime": end_time,
            "executionTime": execution_time,
            "aggregate_metrics": test_data.get("aggregate_metrics", {}),
            "results": test_data.get("results", []),
            "successful_questions": test_data.get("successful_questions", 0),
            "failed_questions": test_data.get("failed_questions", 0)
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to get RAGAS batch status: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to get status: {str(e)}")


@router.get("/list", summary="List All RAGAS Tests")
async def list_ragas_tests(http_request: Request, session_id: Optional[str] = None) -> Dict[str, Any]:
    """List all RAGAS test results"""
    try:
        with sqlite3.connect(RAGAS_TEST_DB_PATH) as conn:
            if session_id:
                cursor = conn.execute("""
                    SELECT test_id, data, created_at, updated_at 
                    FROM ragas_test_results 
                    WHERE json_extract(data, '$.session_id') = ?
                    ORDER BY updated_at DESC
                """, (session_id,))
            else:
                cursor = conn.execute("""
                    SELECT test_id, data, created_at, updated_at 
                    FROM ragas_test_results 
                    ORDER BY updated_at DESC
                """)
            
            rows = cursor.fetchall()
            tests = []
            for row in rows:
                test_id, data_json, created_at, updated_at = row
                try:
                    test_data = json.loads(data_json)
                    tests.append({
                        "testId": test_id,
                        "testName": test_data.get("test_name", f"Test {test_id[:8]}"),
                        "status": test_data.get("status", "unknown"),
                        "sessionId": test_data.get("session_id", ""),
                        "startTime": test_data.get("start_time"),
                        "endTime": test_data.get("end_time"),
                        "createdAt": created_at,
                        "updatedAt": updated_at,
                        "totalQuestions": test_data.get("total_questions", 0),
                        "progress": test_data.get("progress", 0)
                    })
                except json.JSONDecodeError:
                    continue
            
            return {
                "success": True,
                "tests": tests,
                "total": len(tests)
            }
    except Exception as e:
        logger.error(f"Failed to list RAGAS tests: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to list tests: {str(e)}")


# Update test name model
class UpdateTestNameRequest(BaseModel):
    """Request model for updating test name"""
    testName: str = Field(..., description="New test name")


@router.get("/export-pdf/{test_id}", summary="Export RAGAS Test Results as PDF")
async def export_ragas_test_pdf(test_id: str, http_request: Request) -> Response:
    """Export RAGAS test results as PDF report"""
    from src.api.main import _require_owner_or_admin
    
    if not REPORTLAB_AVAILABLE:
        raise HTTPException(status_code=503, detail="PDF export not available - reportlab not installed")
    
    try:
        # Load test data
        test_data = RAGAS_TEST_STORAGE.get(test_id)
        if not test_data:
            test_data = _load_ragas_test_from_db(test_id)
            if not test_data:
                raise HTTPException(status_code=404, detail="Test not found")
        
        # Verify access
        _require_owner_or_admin(http_request, test_data.get("session_id", ""))
        
        # Create PDF in memory
        # ReportLab handles Unicode automatically when using Paragraph
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer, 
            pagesize=A4, 
            topMargin=0.5*inch, 
            bottomMargin=0.5*inch
        )
        
        # Helper function to escape HTML and handle Turkish characters
        def escape_html(text):
            """Escape HTML special characters for ReportLab Paragraph, preserving Unicode"""
            if text is None:
                return ""
            # Ensure we have a Unicode string (not bytes)
            if isinstance(text, bytes):
                try:
                    text = text.decode('utf-8')
                except UnicodeDecodeError:
                    text = text.decode('latin-1', errors='ignore')
            # Convert to string, ensuring Unicode
            text = str(text)
            # Replace HTML special characters (but preserve Turkish/Unicode characters)
            # Order matters: & must be first
            text = text.replace("&", "&amp;")
            text = text.replace("<", "&lt;")
            text = text.replace(">", "&gt;")
            text = text.replace('"', "&quot;")
            text = text.replace("'", "&#x27;")
            return text
        
        # Container for the 'Flowable' objects
        elements = []
        styles = getSampleStyleSheet()
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=30,
            alignment=1  # Center
        )
        elements.append(Paragraph(escape_html("RAGAS Test Raporu"), title_style))
        elements.append(Spacer(1, 0.2*inch))
        
        # Test Information
        test_name = test_data.get("test_name", f"Test {test_id[:8]}")
        status = test_data.get("status", "unknown")
        start_time = test_data.get("start_time", "")
        end_time = test_data.get("end_time", "")
        total_questions = test_data.get("total_questions", 0)
        successful_questions = test_data.get("successful_questions", 0)
        failed_questions = test_data.get("failed_questions", 0)
        
        info_data = [
            ["Test Adı:", test_name],
            ["Durum:", status.upper()],
            ["Başlangıç:", start_time[:19] if start_time else "N/A"],
            ["Bitiş:", end_time[:19] if end_time else "N/A"],
            ["Toplam Soru:", str(total_questions)],
            ["Başarılı:", str(successful_questions)],
            ["Başarısız:", str(failed_questions)],
        ]
        
        # Convert table data to Paragraphs for Unicode support
        info_table_data = []
        for row in info_data:
            info_table_data.append([
                Paragraph(escape_html(row[0]), styles['Normal']),
                Paragraph(escape_html(row[1]), styles['Normal'])
            ])
        
        info_table = Table(info_table_data, colWidths=[2*inch, 4*inch])
        info_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f5f5f5')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        elements.append(info_table)
        elements.append(Spacer(1, 0.3*inch))
        
        # Aggregate Metrics
        aggregate_metrics = test_data.get("aggregate_metrics", {})
        if aggregate_metrics:
            elements.append(Paragraph(escape_html("Ortalama Metrikler"), styles['Heading2']))
            elements.append(Spacer(1, 0.1*inch))
            
            metrics_data = [["Metrik", "Skor (%)"]]
            if aggregate_metrics.get("average_faithfulness") is not None:
                metrics_data.append(["Faithfulness", f"{aggregate_metrics['average_faithfulness']*100:.1f}%"])
            if aggregate_metrics.get("average_answer_relevancy") is not None:
                metrics_data.append(["Answer Relevancy", f"{aggregate_metrics['average_answer_relevancy']*100:.1f}%"])
            if aggregate_metrics.get("average_context_precision") is not None:
                metrics_data.append(["Context Precision", f"{aggregate_metrics['average_context_precision']*100:.1f}%"])
            if aggregate_metrics.get("average_context_recall") is not None:
                metrics_data.append(["Context Recall", f"{aggregate_metrics['average_context_recall']*100:.1f}%"])
            if aggregate_metrics.get("average_overall_score") is not None:
                metrics_data.append(["Genel Skor", f"{aggregate_metrics['average_overall_score']*100:.1f}%"])
            
            # Convert table data to Paragraphs for Unicode support
            metrics_table_data = []
            for row in metrics_data:
                metrics_table_data.append([
                    Paragraph(escape_html(row[0]), styles['Normal']),
                    Paragraph(escape_html(row[1]), styles['Normal'])
                ])
            
            metrics_table = Table(metrics_table_data, colWidths=[3*inch, 3*inch])
            metrics_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4a5568')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('FONTSIZE', (0, 1), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9f9f9')]),
            ]))
            elements.append(metrics_table)
            elements.append(Spacer(1, 0.3*inch))
        
        # Detailed Results
        results = test_data.get("results", [])
        if results:
            elements.append(Paragraph(escape_html("Detaylı Sonuçlar"), styles['Heading2']))
            elements.append(Spacer(1, 0.1*inch))
            
            for idx, result in enumerate(results[:50], 1):  # Limit to first 50 for PDF size
                if idx > 1:
                    elements.append(Spacer(1, 0.2*inch))
                
                question = result.get("question", "")
                answer = result.get("answer", "")
                ragas_metrics = result.get("ragas_metrics", {})
                success = result.get("success", False)
                
                # Question header
                question_style = ParagraphStyle(
                    'QuestionStyle',
                    parent=styles['Heading3'],
                    fontSize=12,
                    textColor=colors.HexColor('#2d3748'),
                    spaceAfter=6,
                )
                elements.append(Paragraph(escape_html(f"{idx}. {question}"), question_style))
                
                # Metrics table for this question
                q_metrics_data = [["Metrik", "Skor (%)"]]
                if ragas_metrics.get("faithfulness") is not None:
                    q_metrics_data.append(["Faithfulness", f"{ragas_metrics['faithfulness']*100:.1f}%"])
                if ragas_metrics.get("answer_relevancy") is not None:
                    q_metrics_data.append(["Answer Relevancy", f"{ragas_metrics['answer_relevancy']*100:.1f}%"])
                if ragas_metrics.get("context_precision") is not None:
                    q_metrics_data.append(["Context Precision", f"{ragas_metrics['context_precision']*100:.1f}%"])
                if ragas_metrics.get("context_recall") is not None:
                    q_metrics_data.append(["Context Recall", f"{ragas_metrics['context_recall']*100:.1f}%"])
                if ragas_metrics.get("overall_score") is not None:
                    q_metrics_data.append(["Genel Skor", f"{ragas_metrics['overall_score']*100:.1f}%"])
                
                # Convert table data to Paragraphs for Unicode support
                q_metrics_table_data = []
                for row in q_metrics_data:
                    q_metrics_table_data.append([
                        Paragraph(escape_html(row[0]), styles['Normal']),
                        Paragraph(escape_html(row[1]), styles['Normal'])
                    ])
                
                q_metrics_table = Table(q_metrics_table_data, colWidths=[2.5*inch, 3.5*inch])
                q_metrics_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e2e8f0')),
                    ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                    ('TOPPADDING', (0, 0), (-1, -1), 6),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ]))
                elements.append(q_metrics_table)
                
                # Answer preview (truncated)
                if answer:
                    answer_style = ParagraphStyle(
                        'AnswerStyle',
                        parent=styles['Normal'],
                        fontSize=9,
                        textColor=colors.HexColor('#4a5568'),
                        spaceBefore=6,
                        spaceAfter=6,
                    )
                    answer_preview = answer[:200] + "..." if len(answer) > 200 else answer
                    elements.append(Paragraph(f"<b>Cevap:</b> {answer_preview}", answer_style))
                
                if not success:
                    error = result.get("error", "Unknown error")
                    error_style = ParagraphStyle(
                        'ErrorStyle',
                        parent=styles['Normal'],
                        fontSize=9,
                        textColor=colors.red,
                        spaceBefore=6,
                    )
                    elements.append(Paragraph(f"<b>Hata:</b> {error}", error_style))
                
                if idx >= 50:
                    elements.append(Spacer(1, 0.2*inch))
                    elements.append(Paragraph(f"<i>Not: Toplam {len(results)} soru var, ilk 50 soru gösteriliyor.</i>", styles['Normal']))
                    break
        
        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        
        # Return PDF as response
        # Clean filename: remove Turkish characters and special chars for safe filename
        import re
        safe_test_name = re.sub(r'[^\w\s-]', '', test_name).strip()
        safe_test_name = safe_test_name.replace(' ', '_')
        # Remove Turkish characters for filename (keep content with Turkish chars)
        turkish_char_map = {
            'ş': 's', 'Ş': 'S', 'ğ': 'g', 'Ğ': 'G',
            'ü': 'u', 'Ü': 'U', 'ö': 'o', 'Ö': 'O',
            'ç': 'c', 'Ç': 'C', 'ı': 'i', 'İ': 'I'
        }
        for tr_char, en_char in turkish_char_map.items():
            safe_test_name = safe_test_name.replace(tr_char, en_char)
        
        filename = f"ragas_test_{test_id[:8]}_{safe_test_name[:50]}.pdf"
        
        # Use RFC 5987 encoding for filename with Turkish characters in Content-Disposition
        from urllib.parse import quote
        encoded_filename = quote(test_name.encode('utf-8'))
        safe_filename = filename.encode('ascii', 'ignore').decode('ascii')
        
        return Response(
            content=buffer.getvalue(),
            media_type="application/pdf",
            headers={
                "Content-Disposition": f'attachment; filename="{safe_filename}"; filename*=UTF-8\'\'{encoded_filename}.pdf'
            }
        )
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to generate PDF for test {test_id}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to generate PDF: {str(e)}")


@router.put("/update/{test_id}", summary="Update RAGAS Test")
async def update_ragas_test(test_id: str, request: UpdateTestNameRequest, http_request: Request) -> Dict[str, Any]:
    """Update RAGAS test name"""
    from src.api.main import _require_owner_or_admin
    
    try:
        # Load test data
        test_data = RAGAS_TEST_STORAGE.get(test_id)
        if not test_data:
            test_data = _load_ragas_test_from_db(test_id)
            if not test_data:
                raise HTTPException(status_code=404, detail="Test not found")
        
        # Verify access
        _require_owner_or_admin(http_request, test_data.get("session_id", ""))
        
        # Update test name
        test_data["test_name"] = request.testName
        
        # Save to DB and memory
        _save_ragas_test_to_db(test_id, test_data)
        
        logger.info(f"✅ Updated test {test_id} name to: {request.testName}")
        
        return {
            "success": True,
            "testId": test_id,
            "testName": request.testName,
            "message": "Test updated successfully"
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to update test {test_id}: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to update test: {str(e)}")


@router.delete("/delete/{test_id}", summary="Delete RAGAS Test")
async def delete_ragas_test(test_id: str, http_request: Request) -> Dict[str, Any]:
    """Delete RAGAS test"""
    from src.api.main import _require_owner_or_admin
    
    try:
        # Load test data to verify access
        test_data = RAGAS_TEST_STORAGE.get(test_id)
        if not test_data:
            test_data = _load_ragas_test_from_db(test_id)
            if not test_data:
                raise HTTPException(status_code=404, detail="Test not found")
        
        # Verify access
        _require_owner_or_admin(http_request, test_data.get("session_id", ""))
        
        # Delete from database
        with sqlite3.connect(RAGAS_TEST_DB_PATH) as conn:
            conn.execute("DELETE FROM ragas_test_results WHERE test_id = ?", (test_id,))
        
        # Delete from memory
        if test_id in RAGAS_TEST_STORAGE:
            del RAGAS_TEST_STORAGE[test_id]
        
        logger.info(f"🗑️ Deleted test {test_id}")
        
        return {
            "success": True,
            "testId": test_id,
            "message": "Test deleted successfully"
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to delete test {test_id}: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to delete test: {str(e)}")


@router.post("/evaluate-batch")
async def evaluate_rag_batch(requests: List[RAGASEvaluationRequest]):
    """
    Evaluate multiple RAG queries in batch
    
    This endpoint evaluates multiple question-answer pairs and returns
    aggregated metrics.
    """
    try:
        logger.info(f"Evaluating batch of {len(requests)} RAG queries")
        
        results = []
        for i, req in enumerate(requests):
            try:
                # Use the single evaluation endpoint
                result = await evaluate_rag(req)
                results.append({
                    "index": i,
                    "question": req.question,
                    "result": result.dict(),
                    "success": True
                })
            except Exception as e:
                logger.error(f"Failed to evaluate query {i}: {e}")
                results.append({
                    "index": i,
                    "question": req.question,
                    "error": str(e),
                    "success": False
                })
        
        # Calculate aggregate metrics
        successful_results = [r for r in results if r.get("success")]
        if successful_results:
            avg_faithfulness = sum(r["result"]["faithfulness"] for r in successful_results) / len(successful_results)
            avg_answer_relevancy = sum(r["result"]["answer_relevancy"] for r in successful_results) / len(successful_results)
            avg_overall = sum(r["result"]["overall_score"] for r in successful_results) / len(successful_results)
            
            # Calculate context metrics if available
            context_results = [r for r in successful_results if r["result"].get("context_precision") is not None]
            avg_context_precision = None
            avg_context_recall = None
            if context_results:
                avg_context_precision = sum(r["result"]["context_precision"] for r in context_results) / len(context_results)
                avg_context_recall = sum(r["result"]["context_recall"] for r in context_results) / len(context_results)
            
            return {
                "total_queries": len(requests),
                "successful": len(successful_results),
                "failed": len(requests) - len(successful_results),
                "aggregate_metrics": {
                    "average_faithfulness": avg_faithfulness,
                    "average_answer_relevancy": avg_answer_relevancy,
                    "average_context_precision": avg_context_precision,
                    "average_context_recall": avg_context_recall,
                    "average_overall_score": avg_overall
                },
                "results": results
            }
        else:
            return {
                "total_queries": len(requests),
                "successful": 0,
                "failed": len(requests),
                "error": "All evaluations failed",
                "results": results
            }
            
    except Exception as e:
        logger.error(f"Batch evaluation error: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Batch evaluation failed: {str(e)}"
        )

